[package]
name = "stuffr-cli"
version.workspace = true
description = "The stuffr command line interface"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stuffr"
path = "src/main.rs"

[dependencies]
stuffr = { path = "../stuffr", version = "0.1.0", features = ["serde"] }
clap = { workspace = true }
serde_json = "1"
