[package]
name = "stuffr-cli"
version.workspace = true
description = "The stf command line interface"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stf"
path = "src/main.rs"

[dependencies]
stuffr = { path = "../stuffr", version = "0.0.1" }
